name: test2 Name
slug: test2-name-test-2-nummer
client: fzag-staging
project_number: Test 2 Nummer
languages:
- de
- fr
- it
- en
default_language: de
description:
  de: test2 Name
  en: test2 Name
master_slug: master-standard
master_version: v20260818
